# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 1.15.2-26.2
maven_group = net.frostbyte.slabsandstairs
archives_base_name = slabsandstairs

# Dependencies
fabric_api_version=0.160.0+26.2